version: '1.0'

services:
  # Raspberry PI onboard I/O
  pi_onboard:
    image: nisse/pi_onboard:1.0
    configuration:
      inputs:
        - name: "Main Entry PIR"
          area: "Main Area"
          resistance_alarm: 5000
          resistance_bias: 5000
          resistance_tamper: 10000
          tolerance: 2
          behaviors:
          - name: "Alert when Armed"
        - name: "Backroom PIR"
          area: "Main Area"
          resistance_alarm: 5000
          resistance_bias: 5000
          resistance_tamper: 10000
          tolerance: 2
          behaviors:
          - name: "Alert when Armed"
      outputs:
        - name: "Front Siren"
          area: "Main Area"
        - name: "Entry Lights"
          area: "Main Area"
          behaviors:
          - name: "Activate on Schedule"
            schedule: "9 to 5"
      device:
        - name: "Local Device"
          area: "Main Area"
          behaviors:
          - name: "Alert on Offline"
            
        
  # Axis Door Controller
  axis_doorcontroller:
    image: nisse/axis_doorcontroller:1.0
    configuration:
      doors:
        - name: "Front Door"
          area: "Main Area"
          strike_time: 10s
          enable_ajar: yes
          enable_forced: yes
        - name: "Back Door"
          area: "Main Area"
          strike_time: 10s
      readers:
        - name: "Reader - Front Door Outside"
          area: "Main Area"
      
areas:
  - name: "Main Area"
    entry_delay: 30s
    exit_delay: 30s
 
schedules:
  - name: "9 to 5"
    monday:
      - "9:00 to 17:00"
    tuesday:
      - "9:00 to 17:00"
    wednesday:
      - "9:00 to 17:00"
    thursday:
      - "9:00 to 17:00"
    friday:
      - "9:00 to 17:00"
    saturday:
      - "9:00 to 17:00"
    sunday:
      - "9:00 to 17:00"
    holiday1:
      - "9:00 to 17:00"
    holiday2:
      - "9:00 to 17:00"
    holiday3:
      - "9:00 to 17:00"

alerts:
  - name: "Burglar"
    priority: 20
  - name: "Communication"
    priority: 
  - name: "Fault"
    priority: 10
